version: '3'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: mc-valhelsia
    ports:
      - "25570:25565"
      - "25575:25575"
    volumes:
      - "mc-data:/data"
    environment:
      EULA: "TRUE"
      CONSOLE: "false"
      ENABLE_RCON: "false"
      ENABLE_QUERY: "false"
      MAX_PLAYERS: 10
      OPS: "plexuss,Aralito99"
      DIFFICULTY: "normal"
      SNOOPER_ENABLED: "false"
      VIEW_DISTANCE: 12
      # SEED: 747624897180923234
      MODE: "survival"
      MOTD: "MC Valhesia 3 Server"
      PVP: "true"
      FORGEVERSION: "36.0.45"
      VERSION: "1.16.5"
      TYPE: "FORGE"
      MEMORY: "4G"
      # MEMORY: "3G"
    restart: always
    stdin_open: true
    tty: true

volumes:
  mc-data:
